Acceptance tests fix
kentik/terraform-provider-kentik-cloudexport pull request #102
Opened 2022-06-24 08:01 UTC by jdziurzynski

KNTK-349
Acceptance tests workflow fix.

TF_ACC_PREFIX is now correctly assigned.
Additional deletion of resources created during tests.

2022-06-27 09:01 UTC, mateuszmidor submitted a review, later dismissed

2022-06-27 09:02 UTC, mateuszmidor reviewed
I like the resources cleanup addition

2022-06-27 18:23 UTC, mmac-m3a requested changes
The segfault on name collision needs to be fixed. The test should fail cleanly reporting the error returned by the Kentik API.

So, instead of:
```
--- FAIL: TestAccDataSourceCloudExportItemAWS (0.87s)
    data_source_cloudexport_item_test.go:229: 
        	Error Trace:	data_source_cloudexport_item_test.go:229
        	Error:      	Received unexpected error:
        	            	client.CloudExports.Create: rpc error: code = Internal desc = internal error (name:DuplicateKeyError type:object) (errxid cats2xv7panhvcx3hb20)
        	Test:       	TestAccDataSourceCloudExportItemAWS
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xbc3b9e]
```
it should report just:
```
rpc error: code = Internal desc = internal error (name:DuplicateKeyError type:object) (errxid cats2xv7panhvcx3hb20)
        	Test:       	TestAccDataSourceCloudExportItemAWS
```
(or something close to that).

Let' make the fix in this PR, while the problem is still easy to reproduce.

2022-06-28 10:32 UTC, jdziurzynski commented on internal/provider/data_source_cloudexport_list_test.go
> +		ceAWS, err := client.CloudExports.Create(ctx, newAWSCloudExportListForAccTest())
Problem with panic should not occur anymore. In this PR I have changed the code to break the test when CloudExport client returns any error.
I tried to reproduce a similar situation with DuplicateKeyError and this is what I got:
```
?       github.com/kentik/terraform-provider-kentik-cloudexport [no test files]
--- FAIL: TestAccDataSourceCloudExportItemAWS (1.93s)
    data_source_cloudexport_item_test.go:234: 
                Error Trace:    data_source_cloudexport_item_test.go:234
                Error:          Received unexpected error:
                                rpc error: code = Internal desc = internal error (name:DuplicateKeyError type:object) (errxid caxcykjp64h36pan8fqg)
                Test:           TestAccDataSourceCloudExportItemAWS
FAIL
FAIL    github.com/kentik/terraform-provider-kentik-cloudexport/internal/provider       25.982s
FAIL
```
The last acceptance test was run by pull_request_target action and I think it run tests on the master branch, thats why we got panic.

2022-06-28 10:41 UTC, jdziurzynski commented on internal/provider/data_source_cloudexport_list_test.go
> +		ceAWS, err := client.CloudExports.Create(ctx, newAWSCloudExportListForAccTest())
TestAccDataSourceCloudExportList checks the kentik-cloudexport_list data source method. For this test, I created only two simple resources to check if kentik-cloudexport_list returns a resource list.
More advanced tests for all providers can be found at data_source_cloudexport_item_test.go

2022-06-28 15:43 UTC, merged