Additional provider validation
kentik/terraform-provider-kentik-cloudexport pull request #86
Opened 2022-05-25 13:54 UTC by jdziurzynski

KNTK-390

Added validation to few fields on provider schema.

2022-06-10 01:53 UTC, mmac-m3a approved these changes
LGTM

2022-06-10 01:53 UTC, mmac-m3a commented
I'll wait for @danielfurman to review the PR before merging it.

2022-06-14 13:32 UTC, danielfurman commented on internal/provider/cloudexport_schema.go
> +			models.CloudProviderAWS,
Could you explain what is the purpose of that? And why we have 4 values here?
I understand that this is a 1-element list of AWS object, so I don't know how ExactlyOneOf applies to this.

2022-06-14 14:21 UTC, danielfurman requested changes

2022-06-14 14:21 UTC, danielfurman commented on internal/provider/cloudexport_schema.go
> +			models.CloudProviderAWS,
As discussed in other channel, this is for validation that there is only one object with provider properties. We need to use separate awsKey constant to make it readable.

2022-06-20 12:40 UTC, danielfurman commented on internal/provider/cloudexport_schema.go
> +			models.CloudProviderAWS,
Done

2022-06-20 12:41 UTC, danielfurman approved these changes

2022-06-21 17:24 UTC, mmac-m3a approved these changes

2022-06-21 17:25 UTC, merged